/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppVendasRouteImport } from './routes/_app.vendas'
import { Route as AppRepassesRouteImport } from './routes/_app.repasses'
import { Route as AppProdutosRouteImport } from './routes/_app.produtos'
import { Route as AppEntradasRouteImport } from './routes/_app.entradas'
import { Route as AppClientesRouteImport } from './routes/_app.clientes'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppVendasRoute = AppVendasRouteImport.update({
  id: '/vendas',
  path: '/vendas',
  getParentRoute: () => AppRoute,
} as any)
const AppRepassesRoute = AppRepassesRouteImport.update({
  id: '/repasses',
  path: '/repasses',
  getParentRoute: () => AppRoute,
} as any)
const AppProdutosRoute = AppProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => AppRoute,
} as any)
const AppEntradasRoute = AppEntradasRouteImport.update({
  id: '/entradas',
  path: '/entradas',
  getParentRoute: () => AppRoute,
} as any)
const AppClientesRoute = AppClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/clientes': typeof AppClientesRoute
  '/entradas': typeof AppEntradasRoute
  '/produtos': typeof AppProdutosRoute
  '/repasses': typeof AppRepassesRoute
  '/vendas': typeof AppVendasRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/clientes': typeof AppClientesRoute
  '/entradas': typeof AppEntradasRoute
  '/produtos': typeof AppProdutosRoute
  '/repasses': typeof AppRepassesRoute
  '/vendas': typeof AppVendasRoute
  '/': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/clientes': typeof AppClientesRoute
  '/_app/entradas': typeof AppEntradasRoute
  '/_app/produtos': typeof AppProdutosRoute
  '/_app/repasses': typeof AppRepassesRoute
  '/_app/vendas': typeof AppVendasRoute
  '/_app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/clientes'
    | '/entradas'
    | '/produtos'
    | '/repasses'
    | '/vendas'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/clientes'
    | '/entradas'
    | '/produtos'
    | '/repasses'
    | '/vendas'
    | '/'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/clientes'
    | '/_app/entradas'
    | '/_app/produtos'
    | '/_app/repasses'
    | '/_app/vendas'
    | '/_app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/vendas': {
      id: '/_app/vendas'
      path: '/vendas'
      fullPath: '/vendas'
      preLoaderRoute: typeof AppVendasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/repasses': {
      id: '/_app/repasses'
      path: '/repasses'
      fullPath: '/repasses'
      preLoaderRoute: typeof AppRepassesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/produtos': {
      id: '/_app/produtos'
      path: '/produtos'
      fullPath: '/produtos'
      preLoaderRoute: typeof AppProdutosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/entradas': {
      id: '/_app/entradas'
      path: '/entradas'
      fullPath: '/entradas'
      preLoaderRoute: typeof AppEntradasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/clientes': {
      id: '/_app/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof AppClientesRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppClientesRoute: typeof AppClientesRoute
  AppEntradasRoute: typeof AppEntradasRoute
  AppProdutosRoute: typeof AppProdutosRoute
  AppRepassesRoute: typeof AppRepassesRoute
  AppVendasRoute: typeof AppVendasRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppClientesRoute: AppClientesRoute,
  AppEntradasRoute: AppEntradasRoute,
  AppProdutosRoute: AppProdutosRoute,
  AppRepassesRoute: AppRepassesRoute,
  AppVendasRoute: AppVendasRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
